### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by Shinta2018** [Shathra/comparing-trajectory-clustering-methods#1]
Hi!

Many thanks for your sharing!
I'm testing your codes. In the codes the files such as 'dense.dat', '1_traj_seg.dt', 'distance1.npz' and 'gaussian_representation.dat' are loaded and they are missing here. Could you please upload them? Many thanks!

Cheers!

**Comment by seljukgulcan** [comment]
Hello,

I'm probably not allowed to upload the datasets and I guess some data transformation scripts are missing in the repo. The most important data file is `distance1.npz` which stores all pairwise haussdorf distances in a numpy array format. If you tell me which part of the code you are interested in, I can provide some toy data that runs the code without any error.

**Comment by ztypaker** [comment]
thanks for your sharing.i couldn't get the file name hdbscan.py.Could you upload it?
and the data file like distance1.npz,~.dt isn't here too.
thanks a lot @Shathra

**Comment by ztypaker** [comment]
hello.could you get dbscan.py? @Shinta2018

**Comment by seljukgulcan** [comment]
@ztypaker , dbscan is from [scikit-learn](https://scikit-learn.org/stable/) library and you can get hdbscan from [this link](https://github.com/scikit-learn-contrib/hdbscan). Unfortunately, I cannot upload project data. However, I added a [notebook](https://github.com/Shathra/comparing-trajectory-clustering-methods/blob/master/demo/demo.ipynb) which shows every crucial part I applied in the project in a much simpler way, on a publicly available data. Please look at that and let me know if you have any further question.

**Comment by veronicasr9** [comment]
thanks for your sharing. when i run the demo i couldn't open the URL of"dataset_link". 
maybe it is  a intranet?now  I couldn't get the database....If it's convenient, could you please send me a dataset? my e-mail is helanshen199@gmail.com.
I look forward to your reply. Thank you very much.

**Comment by seljukgulcan** [comment]
@veronicasr9 , the dataset is not mine, it is a public dataset located here: http://cvrr.ucsd.edu/bmorris/datasets/dataset_trajectory_clustering.html. You can download it manually if download script is not working for some reasons.

**Comment by veronicasr9** [comment]
It's done! Thank you very much for your help!
