### ISSUE TITLE
I‘m a beginer for Python and need some help

### ISSUE THREAD

**Issue by Baoxin1997** [Shathra/comparing-trajectory-clustering-methods#2]
hi, Shathra
I download the code zip, but i don't know how to run it for my own GPS trajectory data, could you help me to analyze my data? My data include track ID, longitude, latitude and timestamp.
If here is not convenient answer, you can contact me with 1359935440@qq.com.
look forward and really thanks for your help!

**Comment by seljukgulcan** [comment]
Hello, Baoxin1997,

You can look at https://github.com/Shathra/comparing-trajectory-clustering-methods/blob/master/demo/demo.ipynb for a start. If you can convert your data into the format described on the link (each trajectory should be (N, 2) shaped NumPy array), then the code should work. To do that, you may need to group your data by track ID and sort by timestamp. Please check out a NumPy quickstart tutorial if you don't know how to import, edit, sort, etc. an array using Numpy.

Also, euclidian distance doesn't make sense for polar coordinates. You may need to either use haversine distance or project your coordinates into a cartesian plane. The latter may not work if you are working on world-scale data. For more information, you can look at this wiki page: https://en.wikipedia.org/wiki/Geographic_coordinate_system#Grid_coordinates

**Comment by Baoxin1997** [comment]
Really thanks for your help!


As you told me, I change the data in to NumPy array with MATLAB. So, how to change the code into read my local file?


look forward your reply

**Comment by seljukgulcan** [comment]
Sorry, I'm not familiar with MATLAB. If you have a file that NumPy can import, you can import with numpy.load or numpy.loadtxt depending on the format of the file. Please refer to the corresponding documentation pages for more info.

**Comment by Baoxin1997** [comment]
Ok, I will try for it. Also, I make a dataset like you give me in demo, especially the 'cross.mat' one. If I want to use this file, how could I do for it? Because in demo code, you dwonload the dataset with a link not use a local file.

**Comment by seljukgulcan** [comment]
These are the lines you're looking for. Depending on your data, you may need to tweak some lines. After importing and preprocessing your data, `traj_lst` object should be a list of trajectories where each trajectory is represented by a `(N, 2)` NumPy array.

```
# Import dataset
traj_data = scipy.io.loadmat(filename)['tracks']

traj_lst = []
for data_instance in traj_data:
    traj_lst.append(np.vstack(data_instance[0]).T)
```

If it doesn't work please provide a sample output you get after you load your file with `scipy.io.loadmat` function. 

Edit: 'track' key in the code might be something else for your data.

**Comment by Baoxin1997** [comment]
Really*N thanks!

I finish my work perfectly with your help. You are really kindly for me.

Let me thank you again!
