### ISSUE TITLE
data link

### ISSUE THREAD

**Issue by hananeYS** [Shathra/comparing-trajectory-clustering-methods#6]
The link of the data doesn't works

**Comment by seljukgulcan** [comment]
They changed the address. I'm pasting the new address below. Soon, I'll update the repo accordingly.

http://cvrr-nas.ucsd.edu/bmorris/datasets/dataset_trajectory_clustering.html

**Comment by hananeYS** [comment]
> They changed the address. I'm pasting the new address below. Soon, I'll update the repo accordingly.
> 
> http://cvrr-nas.ucsd.edu/bmorris/datasets/dataset_trajectory_clustering.html

Thank you, but still not working. we can't download the zip file. Could you please share the dataset in a drive? 
Thank u

**Comment by seljukgulcan** [comment]
Try this http://cvrr-nas.ucsd.edu/LISA/Datasets/TrajectoryClustering/CVRR_dataset_trajectory_clustering.zip

**Comment by hananeYS** [comment]
> Try this http://cvrr-nas.ucsd.edu/LISA/Datasets/TrajectoryClustering/CVRR_dataset_trajectory_clustering.zip

Perfect! thank you very much....

**Comment by sonwe1e** [comment]
> Try this http://cvrr-nas.ucsd.edu/LISA/Datasets/TrajectoryClustering/CVRR_dataset_trajectory_clustering.zip

Sorry, I still can't get data from this link...

**Comment by seljukgulcan** [comment]
I don't know why but they keep changing their domain address. Please send me an email, I can forward the dataset to your mail address.

**Comment by sonwe1e** [comment]
> 

Thank you so much! My mail is sonwe1e@outlook.com.

**Comment by seljukgulcan** [comment]
Sent.

**Comment by mengyue-yuan** [comment]
Hello, I tried to get the data but the link is invalid. Could you please provide a new link or forward the dataset to my email? My email is mengyueyuan@whu.edu.cn. Thank you so much!

**Comment by seljukgulcan** [comment]
Hi @yuanmengyue5566, you should've received the mail. If anyone else faces the same problem, please try [this link](https://seljuk.me/upload/CVRR_dataset_trajectory_clustering.zip).

**Comment by VINCENTWZHENG** [comment]
The data can't find the file called "distance1.npz" . please tell me how to solve it.  Thank you so much

**Comment by seljukgulcan** [comment]
> The data can't find the file called "distance1.npz" . please tell me how to solve it. Thank you so much

`distance1.npz` stores all pairwise haussdorf distances in a NumPy array format. I don't have the right to share the original dataset. You need to compute it for your own dataset.

Please look at demo file which is located here https://github.com/seljukgulcan/comparing-trajectory-clustering-methods/blob/master/demo/demo.ipynb 

This blog post may also help: https://seljuk.me/notes-on-trajectory-clustering.html 

Let me know if you have any further questions.
