### ISSUE TITLE
This data link is invalid

### ISSUE THREAD

**Issue by River-Zhang** [Shathra/comparing-trajectory-clustering-methods#7]
Could you please send me the data zip, my email is 3190100057@zju.edu.cn. Thanks very much!

**Comment by seljukgulcan** [comment]
try this link https://seljuk.me/upload/CVRR_dataset_trajectory_clustering.zip

**Comment by River-Zhang** [comment]
It works! Thanks a lot!

从 Windows 版邮件发送

发件人: Selçuk Gülcan
发送时间: 2022年5月28日 17:12
收件人: seljukgulcan/comparing-trajectory-clustering-methods
抄送: River-Zhang; Author
主题: Re: [seljukgulcan/comparing-trajectory-clustering-methods] This datalink is invalid (Issue #7)

try this link https://seljuk.me/upload/CVRR_dataset_trajectory_clustering.zip
